"really" = "reely"
"real" = "reel"
"guilty" = "gillty"
"god" = "cod"
"kill" = "krill"
"pwn" = "prawn"
"pawn" = "prawn"
"something" = "somefin"
"nothing" = "nofin"
"whatever" = "waterever"
"sardonic" = "sardinonic"
"feeling" = "eeling"
"hero" = "heroe"
"heroine" = "heroeine"
"row" = "roe"
"impudent" = "shrimpudent"
"routine" = "roetine"
"opportunity" = "opportunaty"
"purchase" = "perchase"
"well" = "whale"
"welcome" = "whalecome"
"hilarious" = "gillarious"
"illegal" = "gillegal"
"debate" = "debait"
"bait" = "fishbait"
"doofus" = "doofish"
"meant" = "manta"
"slammin" = "salmon"
"summon" = "salmon"
"creative" = "crayative"
"creature" = "crayture"
"had" = "haddock"
"mack" = "mackerel"
"choir" = "coral"
"melancholic" = "melancoley"
"melancholy" = "melancoley"
"outrageous" = "outraygeous"
"cuddle" = "cuttle"
"hullabaloo" = "hullabeluga"
"pick" = "pike"
"like" = "pike"
"possible" = "posshipbly"
"possibly" = "possibubbly"
"purpose" = "porpoise"
"prepose" = "porpoise"
"propose" = "porpoise"
"appreciate" = "carppreciate"
"appreciation" = "carppreciation"
"insanity" = "insmanatee"
"it's cool" = "s'chool"
"coy" = "koi"
"hate" = "hake"
"brilliant" = "krilliant"
"crappy" = "crappie"
"hearing" = "herring"
"official" = "ofishial"
"bet" = "betta"
"better" = "betta"
"betcha" = "betta"
"selfish" = "shellfish"
"lmao" = "eelmao"
"lmfao" = "eelmao"
"fantastic" = "fintastic"
"fantasy" = "fintasy"
"fun" = "fin"
"fan" = "fin"
"fine" = "fin"
"find" = "fin"
"hell of it" = "halibut"
"talking" = "glubbing"
"chatting" = "carping"
"lotsa" = "lobsta"
"observations" = "lobstervations"
"fumbling" = "floundering"
"believe" = "bereef"
"practicing" = "pracfishing"
"enemy" = "anemone"
"any" = "anemone"
"body" = "moby"
"simmer" = "swimmer"
"or" = "oar"
"sealed" = "seaeeled"
"basically" = "bassically"
"inaccurate" = "finaccurate"
"important" = "finportant"
"simple" = "shrimple"
"simply" = "shrimply"
"myself" = "myshellf"
"yourself" = "yourshellf"
"shoulder" = "schoalder"
"me know" = "minnow"
"asshole" = "basshole"
"show" = "shoal"
"definitely" = "dolphinitely"
"elated" = "eelated"
"convienent" = "conchvienent"
"concerned" = "conchcerned"
"confused" = "conchfused"
"amscray" = "clamscray"
"more" = "moor"
"moirail" = "moireel"
"kismesis" = "fishmesis"
"auspistice" = "ausfishtice"
"snap" = "snapper"
"must" = "mast"
"wailing" = "whaling"
"special" = "speshell"
"sell" = "shell"
"hell" = "shell"
"muscle" = "mussel"
"go be" = "goby"
"help" = "kelp"
"girl" = "gill"
"endorphins" = "endolphins"
"endorse" = "endorsal"
"friend" = "frond"
"frond" = "fond"
"probubbly" = "probably"
"flipping" = "flippering"
"kidding" = "squidding"
"sure" = "shore"
"moola" = "mola"
"see" = "sea"
"weapon" = "weaprawn"
"appear" = "appier"
"disappear" = "disappier"
"disappeared" = "disaspeared"
"aspire" = "aspear"
"discernible" = "fishcernabubble"
"issues" = "fishues"
"net" = "fishnet"
"place" = "plaice"
"discuss" = "discus"
"clamoring" = "clamering"
"each" = "beach"
"bitch" = "beach"
"specific" = "pacific"
"surgeon" = "sturgeon"
"what are" = "water"
"always" = "alwaves"
"attitude" = "attitide"
"title" = "tidal"
"acquainted" = "aquainted"
"serious" = "searious"
"secret" = "seacret"
"seen" = "sean"
"not" = "naut"
"naughty" = "nauty"
"actually" = "actshoally"
"tidy" = "tidey"
"tad" = "shad"
"totally" = "tidally"
"sanitary" = "sanditary"
"teamwork" = "teamfork"
"gullible" = "seagullible"
"puffing" = "puffin"
"crazy" = "craysea"
"turn" = "tern"
"wish" = "fish"
"wishes" = "fishes"
"lunacy" = "lunasea"
"otherwise" = "otterwise"
"other" = "otter"
"oughta" = "otter"
"outta" = "otter"
"shirk" = "shark"
"stark" = "shark"
"tone of" = "tuna"
"tune" = "tuna"
"boy" = "buoy"
"about" = "aboat"
"bout" = "boat"
"jealous" = "jellyfish"
"what about" = "waterboat"
"haul" = "hull"
"sooner" = "schooner"
"mother fucker" = "glubber fucker"
