name = "Davepetasprite^2"
handle = "N/A"
handle_short = "N/A"

["ee to 33"]
type = "replacement"
subtype = "one-to-one"
start = "ee"
end = "33"

["EE to 33"]
type = "replacement"
subtype = "one-to-one"
start = "EE"
end = "33"
