name = "Horuss Zahhak"
handle = "N/A"
handle_short = "N/A"

["x to %"]
type = "replacement"
subtype = "one-to-one"
start = "x"
end = "%"

["X to %"]
type = "replacement"
subtype = "one-to-one"
start = "X"
end = "%"

["loo to 100"]
type = "replacement"
subtype = "one-to-one"
start = "loo"
end = "100"

["ool to 001"]
type = "replacement"
subtype = "one-to-one"
start = "ool"
end = "001"

["LOO to 100"]
type = "replacement"
subtype = "one-to-one"
start = "LOO"
end = "100"

["OOL to 001"]
type = "replacement"
subtype = "one-to-one"
start = "OOL"
end = "001"
