name = "Meenah Peixes"
handle = "N/A"
handle_short = "N/A"

["E to -E"]
type = "replacement"
subtype = "one-to-one"
start = "E"
end = "-E"

["H to )("]
type = "replacement"
subtype = "one-to-one"
start = "H"
end = ")("

["fish puns"]
type = "puns"
subtype = "substitution"
puns = "Fishpuns"

